"""
Sub-mapping lookup tables for element combination logic.

Each map provides specific element-pair → result mappings with educational reasonings.
All element IDs have been verified against proposed/elements.json (2643 elements).

Usage:
    from sub_mappings import ANIMAL_HEAT_MAP, ANIMAL_WATER_MAP, ...
"""

# =============================================================================
# 1. ANIMAL_HEAT_MAP: animal + heat/fire → cooked/heated result
#    Format: { animal_id: (result_id, reasoning) }
#    Default for unmapped animals → ("meat", "Cooking any animal produces meat")
# =============================================================================
ANIMAL_HEAT_MAP = {
    # Cattle
    "cow": ("steak", "Beef from cattle is one of the world's most popular meats"),
    "buffalo": ("steak", "Buffalo steak is leaner than beef but equally delicious"),
    "bison": ("steak", "Bison meat was a staple food for Native American plains tribes"),
    "yak": ("steak", "Yak meat is a high-protein staple in Tibetan cuisine"),

    # Pigs
    "pig": ("sausage", "Pork is the most widely consumed meat globally — sausage is its iconic form"),
    "boar": ("sausage", "Wild boar sausage is a rustic European delicacy"),
    # (warthog not in game — use boar instead)

    # Poultry
    "chicken": ("roast", "Roast chicken is the universal comfort food across cultures"),
    "turkey": ("roast", "Roast turkey — the centerpiece of Thanksgiving since 1621"),
    "duck": ("roast", "Peking duck has been roasted in Beijing since the Imperial era"),
    "goose": ("roast", "Roast goose was the traditional Christmas dinner before turkey"),
    "rooster": ("roast", "Coq au vin transforms tough rooster into a tender French classic"),
    "quail": ("roast", "Roasted quail is a delicate game bird served in fine dining"),

    # Fish
    "fish": ("sushi", "Fish + heat can go many ways, but sushi celebrates the fish itself"),
    "flying-fish": ("roast", "Flying fish are caught and grilled in Caribbean cuisine"),
    "swordfish": ("steak", "Swordfish steaks are meaty enough to grill like beef"),
    "barracuda": ("jerky", "Barracuda is often dried into jerky in Caribbean cuisine"),
    "piranha": ("soup", "In the Amazon, piranha soup is considered a hangover cure"),
    "trout": ("roast", "Pan-roasted trout with almonds — a French classic"),
    "eel": ("sushi", "Unagi (grilled eel) is one of the most prized sushi toppings"),
    "goldfish": ("roast", "Technically edible but please don't — they're pets!"),

    # Sheep/Goat family
    "sheep": ("kebab", "Lamb kebab is the king of Middle Eastern street food"),
    "ram": ("kebab", "Ram meat makes hearty kebabs in Central Asian cuisine"),

    # Deer family
    "deer": ("jerky", "Venison jerky — how frontier settlers preserved their hunt"),
    "elk": ("jerky", "Elk jerky is a prized high-protein snack in the American West"),
    "caribou": ("jerky", "Inuit peoples have dried caribou meat for millennia"),
    "moose": ("jerky", "Moose jerky is a Canadian wilderness tradition"),

    # Shellfish
    "lobster": ("scallop", "Cooked lobster turns bright red — a heat-triggered protein change"),
    "crab": ("scallop", "Steamed crab is a Chesapeake Bay institution"),
    "clam": ("stew", "Clam chowder — New England's most heated debate (cream vs tomato)"),

    # Cephalopods
    "squid": ("tempura", "Calamari (fried squid) — the universal appetizer"),
    "octopus": ("tempura", "Grilled octopus is a Mediterranean taverna essential"),

    # Other specific animals
    "bear": ("steak", "Bear steak was a frontier delicacy — Lewis & Clark ate plenty"),
    "rabbit": ("stew", "Rabbit stew has been a peasant staple across Europe for centuries"),
    "frog": ("stew", "Frog legs — a French delicacy since the 12th century"),
    "snake": ("jerky", "Rattlesnake jerky is a genuine Texan novelty snack"),
    "crocodile": ("jerky", "Crocodile jerky is popular in Australian outback cuisine"),
    "turtle": ("soup", "Turtle soup was a luxury dish in Victorian England"),
    "snail": ("fondue", "Escargot in garlic butter — France's most famous mollusk dish"),
    "whale": ("jerky", "Whale jerky (muktuk) is traditional Inuit food"),
    "camel": ("kebab", "Camel kebab is served at celebrations across the Arabian Peninsula"),
    "alpaca": ("jerky", "Alpaca jerky is a lean protein in Andean cuisine"),
    "llama": ("jerky", "Llama charqui — the original jerky, from Quechua language"),
    "ostrich": ("steak", "Ostrich steak is red meat that's lower in fat than chicken"),
    "kangaroo": ("steak", "Kangaroo steak is a lean, sustainable Australian meat"),
    "horse": ("sausage", "Horse sausage (kazylyk) is traditional in Central Asia"),
    "donkey": ("sausage", "Donkey salami is a protected delicacy in Emilia-Romagna, Italy"),
    # goat not in game — sheep/ram cover this category
    "antelope": ("jerky", "Antelope biltong is a Southern African dried meat tradition"),
    "gazelle": ("kebab", "Gazelle meat is a traditional food in North African cuisine"),
    "sparrow": ("roast", "Sparrows were once roasted on skewers in European street markets"),
    "seal": ("jerky", "Seal jerky is a vital food source in Arctic communities"),
    "walrus": ("jerky", "Walrus meat has sustained Inuit peoples for thousands of years"),

    # Default reasoning for unmapped animals
    "_default": ("meat", "Cooking transforms animal protein into edible meat"),
}

# =============================================================================
# 2. ANIMAL_WATER_MAP: animal + water → aquatic adaptation
#    Format: { animal_id: (result_id, reasoning) }
#    Default for land animals → ("fish", "Evolution adapts land creatures to water")
#    Aquatic animals map to themselves or upgraded aquatic form
# =============================================================================
ANIMAL_WATER_MAP = {
    # Classic transformations
    "horse": ("seahorse", "Seahorses got their name from their horse-shaped heads"),
    "dog": ("otter", "Otters are the playful, dog-like swimmers of the river world"),
    "cat": ("seal", "Seals are sometimes called 'sea cats' — sleek aquatic hunters"),
    "snake": ("eel", "Eels are essentially snakes that evolved for ocean life"),
    "lizard": ("crocodile", "Crocodiles are the ultimate aquatic reptile — 200 million years strong"),
    "monkey": ("otter", "Sea otters use tools like monkeys — floating on their backs cracking shells"),
    "elephant": ("hippopotamus", "Hippos are the elephants of the river — massive and surprisingly aquatic"),
    "lion": ("shark", "Great white sharks are the lions of the sea — apex predators"),
    "tiger": ("shark", "Tiger sharks are named for their striped pattern — ocean's ambush predator"),
    "leopard": ("seal", "Leopard seals are the spotted hunters of Antarctic waters"),
    "bear": ("walrus", "Walruses are the bears of the Arctic sea — huge, tusked, and powerful"),
    "wolf": ("orca", "Orcas hunt in packs like wolves — the wolves of the sea"),
    "fox": ("otter", "River otters are as clever and playful as foxes"),
    "deer": ("seahorse", "A deer in water becomes a seahorse — antlers to coronet"),
    "rabbit": ("axolotl", "Axolotls are the cute, wide-eyed aquatic equivalent of bunnies"),
    "mouse": ("axolotl", "Both mice and axolotls are beloved lab animals — one just breathes water"),
    "rat": ("piranha", "Piranhas are the rats of the Amazon — small, social, and bitey"),
    "cow": ("manatee", "Manatees are called 'sea cows' — gentle, grazing aquatic mammals"),
    "pig": ("hippopotamus", "Hippos wallow in mud and water — aquatic pigs taken to the extreme"),
    "bat": ("flying-fish", "Flying fish leap from the water like bats take to the air"),
    "spider": ("octopus", "Octopuses are the eight-limbed hunters of the deep — sea spiders"),
    "scorpion": ("lobster", "Lobsters are basically underwater scorpions — claws, armor, and all"),
    "ant": ("barnacle", "Barnacles are colonial creatures attached to surfaces — ants of the sea"),
    "bee": ("jellyfish", "Jellyfish sting like bees — both use venom for defense"),
    "butterfly": ("jellyfish", "Jellyfish drift on currents like butterflies float on breeze"),
    "caterpillar": ("sea-cucumber", "Sea cucumbers are the slow, crawling caterpillars of the ocean floor"),
    "worm": ("lamprey", "Lampreys are the worms of the sea — elongated and ancient"),
    "insect": ("crab", "Crabs are essentially ocean insects — both are arthropods"),
    "grasshopper": ("crab", "Crabs are the grasshoppers of the sea — arthropod cousins"),
    "ladybug": ("hermit-crab", "Hermit crabs carry shells like ladybugs carry spotted wing cases"),
    "eagle": ("albatross", "Albatrosses are the eagles of the open ocean — massive wingspan"),
    "falcon": ("kingfisher", "Kingfishers dive-bomb like falcons — but into water"),
    "owl": ("loon", "Loons are the haunting night-callers of lakes — owls of the water"),
    "parrot": ("puffin", "Puffins are the colorful parrots of the sea — bright beaks and all"),
    "penguin": ("penguin", "Penguins are already perfectly adapted to water"),
    "crow": ("cormorant", "Cormorants are dark, intelligent water birds — ocean crows"),
    "chicken": ("duck", "Ducks are what chickens would be if they learned to swim"),
    "turkey": ("goose", "Geese are the aquatic turkeys — big, loud, and territorial"),
    "bird": ("albatross", "Albatrosses spend years at sea without touching land"),
    "gorilla": ("walrus", "Walruses are massive, social marine mammals — gorillas of the sea"),
    "chimpanzee": ("dolphin", "Dolphins rival chimps in intelligence — the brainiacs of the sea"),
    "frog": ("frog", "Frogs are already amphibious — born for water"),
    "salamander": ("axolotl", "Axolotls are salamanders that chose to stay aquatic forever"),
    "turtle": ("turtle", "Sea turtles navigate thousands of miles across oceans"),
    "crocodile": ("crocodile", "Crocodiles are already apex aquatic predators"),
    "iguana": ("iguana", "Marine iguanas of the Galápagos already swim and dive"),
    "shark": ("shark", "Sharks are the ultimate water-adapted predator — 450 million years old"),
    "whale": ("whale", "Whales are already the largest aquatic animals ever"),
    "dolphin": ("dolphin", "Dolphins are already perfectly aquatic — sonar and all"),
    "octopus": ("octopus", "Octopuses are already masters of the deep ocean"),
    "squid": ("squid", "Squid are jet-propelled ocean dwellers already"),
    "jellyfish": ("jellyfish", "Jellyfish are 95% water themselves"),
    "starfish": ("starfish", "Starfish are already aquatic — regenerating arms on the seafloor"),
    "seal": ("seal", "Seals are already superb aquatic mammals"),
    "otter": ("otter", "Otters are already the acrobats of rivers and coasts"),
    "platypus": ("platypus", "Platypuses already swim with webbed feet and electrosensors"),
    "beaver": ("beaver", "Beavers are already nature's aquatic engineers"),
    "hippopotamus": ("hippopotamus", "Hippos spend up to 16 hours a day submerged in water"),
    "manatee": ("manatee", "Manatees are already gentle aquatic grazers"),
    "narwhal": ("narwhal", "Narwhals are already the unicorns of the Arctic sea"),
    # penguin duplicate removed — already listed above

    "_default": ("fish", "Water transforms land creatures toward aquatic life — evolution in action"),
}

# =============================================================================
# 3. ANIMAL_COLD_MAP: animal + cold/ice/snow → cold-adapted version
#    Format: { animal_id: (result_id, reasoning) }
#    Default → ("wool", "Animals grow thick coats to survive the cold")
# =============================================================================
ANIMAL_COLD_MAP = {
    "bear": ("polar-bear", "Polar bears evolved white fur and fat layers for Arctic survival"),
    "fox": ("wolf", "Arctic foxes grow white winter coats — cold makes canines tougher"),
    "cat": ("snow-leopard", "Snow leopards are the ghost cats of the frozen Himalayas"),
    "leopard": ("snow-leopard", "Snow leopards have extra-thick fur and wide paws for mountain snow"),
    "deer": ("caribou", "Caribou are deer perfectly adapted to Arctic tundra — even their noses warm the air"),
    "rabbit": ("rabbit", "Arctic hares turn white in winter — nature's camouflage"),
    "owl": ("owl", "Snowy owls are the white phantoms of the Arctic tundra"),
    "wolf": ("wolf", "Arctic wolves already thrive in -40°C with thick double coats"),
    "whale": ("narwhal", "Narwhals are the tusked whales of the frozen Arctic seas"),
    "elephant": ("dinosaur", "Woolly mammoths were cold-adapted elephants — prehistoric giants of the Ice Age"),
    "dog": ("wolf", "Cold turns dogs back toward their wolf ancestors — built for winter"),
    "horse": ("horse", "Yakutian horses survive -60°C in Siberia with ice-crusted manes"),
    "cow": ("yak", "Yaks are the cold-adapted cattle of the Himalayan highlands"),
    "penguin": ("penguin", "Penguins are already cold-masters — emperor penguins breed at -40°C"),
    "seal": ("walrus", "Walruses have 6 inches of blubber for Arctic insulation"),
    "fish": ("trout", "Cold mountain streams produce the finest trout"),
    "frog": ("frog", "Wood frogs literally freeze solid in winter and thaw alive in spring"),
    "snake": ("snake", "Cold-blooded snakes brumate (hibernate) through winter underground"),
    "lizard": ("iguana", "Marine iguanas in Galápagos have adapted to cold ocean currents"),
    "monkey": ("snow-leopard", "Japanese macaques bathe in hot springs to survive snowy winters"),
    "bird": ("penguin", "Cold pushes birds toward penguin-like adaptations — fat, insulation, huddling"),
    "eagle": ("eagle", "Bald eagles thrive in Alaskan winters — cold sharpens the hunter"),
    "shark": ("narwhal", "Greenland sharks live in near-freezing Arctic waters for 400+ years"),
    "crab": ("crab", "King crabs thrive in frigid Alaskan waters — cold giants"),
    "lobster": ("lobster", "Maine lobsters prefer cold water — it makes them sweeter"),
    "spider": ("spider", "Ice spiders survive Arctic winters with antifreeze proteins in their blood"),
    "bee": ("bee", "Bees huddle in winter clusters, vibrating to generate heat"),
    "ant": ("ant", "Antarctic midge — the only insect native to Antarctica"),
    "crocodile": ("crocodile", "Cold-blooded crocs can't adapt to cold — they'd need to evolve fur"),
    "tiger": ("tiger", "Siberian tigers are the largest cats — cold selects for massive size"),
    "lion": ("lion", "Cave lions once roamed Ice Age Europe alongside mammoths"),
    "goose": ("goose", "Snow geese migrate thousands of miles to Arctic breeding grounds"),
    "duck": ("duck", "Eider ducks produce the world's warmest down — eiderdown"),
    "swan": ("swan", "Tundra swans breed in the Arctic and survive bitter cold"),
    "moose": ("moose", "Moose are already built for cold — they overheat above 5°C"),
    "elk": ("elk", "Elk grow thick winter coats and can paw through snow for food"),
    "caribou": ("caribou", "Caribou are already the ultimate cold-weather deer"),
    "polar-bear": ("polar-bear", "Polar bears are already the apex Arctic predator"),
    "walrus": ("walrus", "Walruses are already adapted to Arctic ice floes"),
    "panda": ("panda", "Giant pandas live in cold mountain bamboo forests"),
    "bison": ("bison", "American bison survived Ice Age winters on the Great Plains"),

    "_default": ("wool", "Cold drives evolution toward thick insulating coats"),
}

# =============================================================================
# 4. ANIMAL_DARK_MAP: animal + dark/darkness → nocturnal version
#    Format: { animal_id: (result_id, reasoning) }
#    Default → ("bat", "Bats are THE iconic nocturnal animal — echolocation in the dark")
# =============================================================================
ANIMAL_DARK_MAP = {
    "bird": ("owl", "Owls are the supreme nocturnal birds — silent flight and night vision"),
    "eagle": ("owl", "Darkness transforms the daytime raptor into a nocturnal hunter"),
    "chicken": ("owl", "From barnyard to the night sky — owls are the nocturnal poultry"),
    "parrot": ("owl", "Night parrots exist but are nearly mythical — owls rule the dark"),
    "mouse": ("bat", "Bats and mice are close relatives — one just took to the night sky"),
    "rat": ("bat", "Bats are basically rats that evolved wings and echolocation"),
    "cat": ("familiar", "Black cats are the witch's familiar — creatures of the night"),
    "dog": ("wolf", "Dogs become wolves in the dark — howling at the moon"),
    "wolf": ("werewolf", "Werewolves embody the terror of wolves in darkness"),
    "insect": ("moth", "Moths are the nocturnal cousins of butterflies — drawn to moonlight"),
    "butterfly": ("moth", "Butterflies become moths at night — trading color for camouflage"),
    "fish": ("anglerfish", "Anglerfish hunt in total darkness with bioluminescent lures"),
    "horse": ("horse", "Nightmares — dark horses of dreams and legend"),
    "snake": ("cobra", "Cobras hunt at dusk — their heat-sensing pits work in total darkness"),
    "lizard": ("chameleon", "Chameleons can turn nearly black to absorb heat in cool darkness"),
    "frog": ("toad", "Toads are the nocturnal, warty cousins of frogs"),
    "rabbit": ("rabbit", "Rabbits are naturally crepuscular — most active at dawn and dusk"),
    "deer": ("deer", "Deer have huge eyes with tapetum lucidum for night vision"),
    "monkey": ("lemur", "Lemurs include many nocturnal species — the ghosts of Madagascar"),
    "bear": ("bear", "Bears are often crepuscular — wandering forests at dusk"),
    "fox": ("fox", "Foxes are naturally nocturnal — their vertical pupils are adapted for darkness"),
    "spider": ("tarantula", "Tarantulas emerge at night to hunt — darkness is their domain"),
    "scorpion": ("scorpion", "Scorpions glow under UV light and hunt exclusively at night"),
    "bee": ("moth", "Darkness transforms pollinators — moths take the night shift"),
    "ant": ("termite", "Termites live in perpetual darkness inside their mounds"),
    "lion": ("leopard", "Leopards are the nocturnal big cats — hunting under cover of darkness"),
    "tiger": ("jaguar", "Jaguars hunt at night in the dark Amazon — nocturnal apex predators"),
    "leopard": ("leopard", "Leopards are already the supreme nocturnal big cat"),
    "owl": ("owl", "Owls are already the masters of the night — supreme darkness predators"),
    "bat": ("bat", "Bats are already the ultimate nocturnal animal"),
    "moth": ("moth", "Moths are already creatures of the night"),
    "shark": ("shark", "Many sharks hunt at night — their electroreception works in total darkness"),
    "octopus": ("octopus", "Octopuses are mostly nocturnal — emerging from dens to hunt at night"),
    "squid": ("squid", "Giant squid live in perpetual deep-sea darkness"),
    "crab": ("crab", "Many crabs are nocturnal scavengers on the seafloor"),
    "crow": ("raven", "Ravens are the darker, more mysterious corvids — omen birds"),
    "elephant": ("elephant", "Elephants sometimes travel at night — they navigate by infrasound"),
    "pig": ("boar", "Wild boars are nocturnal — rooting through forests in darkness"),

    "_default": ("bat", "Bats are THE nocturnal animal — 1,400 species ruling the night sky"),
}

# =============================================================================
# 5. FOOD_FOOD_MAP: specific food + food → combined result
#    Format: { frozenset({food_a, food_b}): (result_id, reasoning) }
#    ~200 entries covering real culinary combinations
# =============================================================================
FOOD_FOOD_MAP = {
    # === Bread combinations ===
    frozenset({"bread", "cheese"}): ("sandwich", "The sandwich — invented by the Earl of Sandwich so he could eat while gambling"),
    frozenset({"bread", "meat"}): ("sandwich", "Meat between bread — the sandwich that changed how the world eats"),
    frozenset({"bread", "butter"}): ("toast", "Buttered toast — humanity's simplest and most satisfying breakfast"),
    frozenset({"bread", "tomato"}): ("bruschetta", "Bruschetta — Italian farmers rubbed tomatoes on grilled bread"),
    frozenset({"bread", "egg-food"}): ("toast", "French toast (pain perdu) — rescuing stale bread with egg"),
    frozenset({"bread", "olive-oil"}): ("focaccia", "Focaccia — Italian flatbread drizzled with olive oil since Roman times"),
    frozenset({"bread", "garlic"}): ("bruschetta", "Garlic bread — the irresistible sidekick to every Italian meal"),
    frozenset({"bread", "chocolate"}): ("crepe", "Pain au chocolat — French bakers put chocolate in everything"),
    frozenset({"bread", "honey"}): ("toast", "Honey on bread — one of humanity's oldest sweet treats"),
    frozenset({"bread", "soup"}): ("stew", "Bread bowls make soup into a complete meal"),

    # === Dough combinations ===
    frozenset({"dough", "cheese"}): ("pizza", "Pizza — Naples gave the world dough + cheese perfection"),
    frozenset({"dough", "tomato"}): ("pizza", "Marinara pizza — the original tomato-on-dough masterpiece"),
    frozenset({"dough", "fruit"}): ("pie", "Fruit pie — the dough-wrapped dessert dating back to ancient Egypt"),
    frozenset({"dough", "meat"}): ("dumpling", "Dumplings — every culture wraps meat in dough differently"),
    frozenset({"dough", "sugar"}): ("cookie", "Cookies — sweetened dough baked into everyone's favorite treat"),
    frozenset({"dough", "butter"}): ("croissant", "Croissants — 27 layers of buttered dough folded to flaky perfection"),
    frozenset({"dough", "honey"}): ("baklava", "Baklava — layers of dough and honey, a Middle Eastern treasure"),
    frozenset({"dough", "spice"}): ("naan", "Naan — spiced flatbread baked in a tandoor oven"),
    frozenset({"dough", "chocolate"}): ("muffin", "Chocolate muffins — sweetened dough's most comforting form"),
    frozenset({"dough", "olive-oil"}): ("focaccia", "Focaccia — olive oil makes the dough tender and golden"),
    frozenset({"dough", "cream"}): ("cream", "Cream-filled doughnuts — the bakery's greatest temptation"),

    # === Pasta combinations ===
    frozenset({"pasta", "tomato"}): ("spaghetti", "Spaghetti al pomodoro — the soul of Italian cooking"),
    frozenset({"pasta", "cheese"}): ("lasagna", "Lasagna — layered pasta and cheese, a Roman legacy"),
    frozenset({"pasta", "meat"}): ("ravioli", "Ravioli — meat stuffed in pasta pillows"),
    frozenset({"pasta", "cream"}): ("lasagna", "Fettuccine Alfredo — cream makes pasta luxurious"),
    frozenset({"pasta", "egg-food"}): ("ravioli", "Egg pasta is richer — the base for fresh ravioli"),
    frozenset({"pasta", "butter"}): ("lasagna", "Pasta al burro — simple buttered pasta is pure comfort"),
    frozenset({"pasta", "garlic"}): ("spaghetti", "Aglio e olio — garlic and pasta, Italy's midnight snack"),
    frozenset({"pasta", "olive-oil"}): ("spaghetti", "Spaghetti aglio e olio — three ingredients, infinite flavor"),
    frozenset({"pasta", "spice"}): ("ramen", "Spiced noodles — from Italian to Asian, pasta loves heat"),
    frozenset({"pasta", "broth"}): ("ramen", "Noodle soup — pasta in broth is comfort in every culture"),
    frozenset({"pasta", "pesto"}): ("spaghetti", "Pesto pasta — Genoa's gift to the world"),

    # === Rice combinations ===
    frozenset({"rice", "fish"}): ("sushi", "Sushi — vinegared rice and fish, Japan's edible art form"),
    frozenset({"rice", "spice"}): ("curry", "Curry and rice — the perfect pairing across all of Asia"),
    frozenset({"rice", "meat"}): ("kebab", "Rice and meat — the base of biryani, pilaf, and paella"),
    frozenset({"rice", "egg-food"}): ("curry", "Egg fried rice — the wok-tossed Chinese classic"),
    frozenset({"rice", "soy-sauce"}): ("sushi", "Soy sauce transforms plain rice into something magical"),
    frozenset({"rice", "cheese"}): ("risotto", "Risotto — Italian rice stirred with cheese into creamy perfection"),
    frozenset({"rice", "broth"}): ("risotto", "Risotto — slowly absorbing broth makes rice incredibly creamy"),
    frozenset({"rice", "milk"}): ("pudding", "Rice pudding — a dessert loved from Scandinavia to India"),
    frozenset({"rice", "bean"}): ("burrito", "Rice and beans — the complete protein combo of the Americas"),
    frozenset({"rice", "vegetable"}): ("stew", "Rice and vegetables — the foundation of healthy eating worldwide"),
    frozenset({"rice", "coconut"}): ("curry", "Coconut rice — fragrant base for tropical curries"),
    frozenset({"rice", "wasabi"}): ("sushi", "Wasabi rice — the spicy foundation of premium sushi"),
    frozenset({"rice", "seaweed"}): ("sushi", "Nori-wrapped rice — the base of every sushi roll"),

    # === Egg combinations ===
    frozenset({"egg-food", "flour"}): ("pasta", "Egg + flour = pasta dough — Italy's most important equation"),
    frozenset({"egg-food", "cheese"}): ("omelette", "Omelettes — the French perfected eggs + cheese into an art form"),
    frozenset({"egg-food", "milk"}): ("custard", "Custard — eggs and milk heated into silky richness"),
    frozenset({"egg-food", "sugar"}): ("meringue", "Meringue — whipped egg whites and sugar become clouds"),
    frozenset({"egg-food", "cream"}): ("custard", "Crème brûlée starts with eggs and cream"),
    frozenset({"egg-food", "butter"}): ("omelette", "Buttery French omelette — eggs cooked in butter is pure luxury"),
    frozenset({"egg-food", "bread"}): ("toast", "Eggs and bread = French toast (pain perdu)"),
    frozenset({"egg-food", "rice"}): ("omelette", "Omurice — Japanese omelette rice, a comfort food icon"),
    frozenset({"egg-food", "potato"}): ("omelette", "Spanish tortilla — eggs and potatoes, tapas perfection"),
    frozenset({"egg-food", "salt"}): ("omelette", "A pinch of salt is all an egg needs to become an omelette"),

    # === Flour combinations ===
    frozenset({"flour", "water"}): ("dough", "Flour + water = dough — the foundation of all baking"),
    frozenset({"flour", "sugar"}): ("cake", "Flour + sugar = the start of every cake and pastry"),
    frozenset({"flour", "butter"}): ("biscuit", "Butter and flour make flaky biscuits and pie crusts"),
    frozenset({"flour", "milk"}): ("batter", "Flour and milk make batter — the base for pancakes and crepes"),
    frozenset({"flour", "egg-food"}): ("pasta", "Flour and eggs — the two-ingredient miracle of fresh pasta"),
    frozenset({"flour", "honey"}): ("cake", "Honey cake — ancient Egypt's favorite dessert"),
    frozenset({"flour", "chocolate"}): ("cake", "Chocolate cake — the world's most popular dessert flavor"),
    frozenset({"flour", "yeast"}): ("bread", "Yeast makes flour rise — the discovery that gave us bread"),
    frozenset({"flour", "oil"}): ("dough", "Oil and flour make tender, pliable dough for flatbreads"),

    # === Milk combinations ===
    frozenset({"milk", "chocolate"}): ("mochi", "Hot chocolate — the Aztecs mixed cacao with liquid 3,500 years ago"),
    frozenset({"milk", "coffee"}): ("espresso", "Café au lait — milk tames coffee into a smooth morning ritual"),
    frozenset({"milk", "tea"}): ("matcha", "Milk tea — from British builders' tea to Taiwanese bubble tea"),
    frozenset({"milk", "sugar"}): ("ice-cream", "Sweetened milk → ice cream — Marco Polo brought the idea from China"),
    frozenset({"milk", "fruit"}): ("smoothie", "Fruit smoothie — blended milk and fruit, the health drink revolution"),
    frozenset({"milk", "honey"}): ("yogurt", "Milk and honey — the promised land's original comfort drink"),
    frozenset({"milk", "cream"}): ("butter", "Churning cream from milk creates butter"),
    frozenset({"milk", "vinegar"}): ("cheese", "Acid + milk = curds — the accidental discovery of cheese-making"),
    frozenset({"milk", "spice"}): ("curry", "Spiced milk drinks are found from Indian chai to golden turmeric lattes"),
    frozenset({"milk", "matcha"}): ("matcha", "Matcha latte — Japanese tea ceremony meets modern café culture"),
    frozenset({"milk", "caramel"}): ("candy", "Caramel milk — dulce de leche, Latin America's sweetest creation"),

    # === Cheese combinations ===
    frozenset({"cheese", "tomato"}): ("pizza", "Cheese + tomato = the two pillars of pizza"),
    frozenset({"cheese", "bread"}): ("sandwich", "Grilled cheese — the ultimate comfort food sandwich"),
    frozenset({"cheese", "meat"}): ("hamburger", "Cheeseburger — America added cheese to Hamburg's patty"),
    frozenset({"cheese", "pasta"}): ("lasagna", "Mac and cheese, lasagna, ravioli — cheese makes all pasta better"),
    frozenset({"cheese", "potato"}): ("fondue", "Cheese and potato — from fondue to loaded baked potatoes"),
    frozenset({"cheese", "cream"}): ("fondue", "Cream cheese — Philadelphia's contribution to cheesecake"),
    frozenset({"cheese", "wine"}): ("fondue", "Fondue — Swiss tradition of melting cheese in wine"),
    frozenset({"cheese", "spice"}): ("nacho", "Spiced cheese dip — nachos were born in 1943 at a Mexican border town"),
    frozenset({"cheese", "corn"}): ("nacho", "Cheese and corn chips = nachos, the stadium snack king"),
    frozenset({"cheese", "rice"}): ("risotto", "Parmesan risotto — cheese makes rice incredibly creamy"),
    frozenset({"cheese", "egg-food"}): ("omelette", "Cheese omelette — a protein-packed breakfast classic"),
    frozenset({"cheese", "flour"}): ("pizza", "Cheese and flour are the backbone of pizza dough and topping"),

    # === Chocolate combinations ===
    frozenset({"chocolate", "milk"}): ("mochi", "Chocolate milk — a beloved childhood drink worldwide"),
    frozenset({"chocolate", "cream"}): ("mousse", "Chocolate mousse — whipped cream and chocolate become clouds of flavor"),
    frozenset({"chocolate", "sugar"}): ("candy", "Chocolate candy — the world's $130 billion confection industry"),
    frozenset({"chocolate", "butter"}): ("truffle", "Chocolate truffles — butter and chocolate ganache, pure indulgence"),
    frozenset({"chocolate", "flour"}): ("cake", "Chocolate cake — the reigning champion of desserts"),
    frozenset({"chocolate", "ice-cream"}): ("mousse", "Chocolate ice cream — the #1 ice cream flavor worldwide"),
    frozenset({"chocolate", "coffee"}): ("tiramisu", "Mocha — chocolate meets coffee in Italian perfection"),
    frozenset({"chocolate", "coconut"}): ("candy", "Bounty bars — chocolate-covered coconut paradise"),
    frozenset({"chocolate", "caramel"}): ("candy", "Chocolate caramels — the Twix/Snickers family of treats"),
    frozenset({"chocolate", "cookie"}): ("cake", "Chocolate chip cookies — Ruth Wakefield's 1938 accident"),
    frozenset({"chocolate", "peanut-butter"}): ("candy", "Reese's cups — the iconic chocolate-PB combo since 1928"),
    frozenset({"chocolate", "mango"}): ("fondue", "Chocolate-dipped tropical fruit — the fondue pot's finest hour"),
    frozenset({"chocolate", "grape"}): ("fondue", "Chocolate-covered grapes — a surprisingly elegant dessert"),

    # === Coffee/Tea combinations ===
    frozenset({"coffee", "milk"}): ("espresso", "Latte — espresso softened with steamed milk"),
    frozenset({"coffee", "chocolate"}): ("tiramisu", "Tiramisu — coffee-soaked ladyfingers meet chocolate mascarpone"),
    frozenset({"coffee", "sugar"}): ("espresso", "Sweet espresso — Italians always add sugar to their shot"),
    frozenset({"coffee", "cream"}): ("espresso", "Café crème — the Parisian morning coffee"),
    frozenset({"coffee", "ice-cream"}): ("tiramisu", "Affogato — espresso poured over gelato, Italy's coffee dessert"),
    frozenset({"tea", "honey"}): ("mead", "Honey tea has been a cold remedy for thousands of years"),
    frozenset({"tea", "milk"}): ("matcha", "Milk tea — a global phenomenon from London to Taipei"),
    frozenset({"tea", "sugar"}): ("kombucha", "Sweet tea — from Southern US sweet tea to kombucha fermentation"),
    frozenset({"tea", "spice"}): ("curry", "Chai — spiced tea is India's most popular drink"),
    frozenset({"tea", "ginger"}): ("kombucha", "Ginger tea — a warming remedy used in traditional medicine"),
    frozenset({"tea", "lemonade"}): ("juice", "Arnold Palmer — half tea, half lemonade, all refreshment"),

    # === Soup/Broth combinations ===
    frozenset({"broth", "noodle"}): ("ramen", "Ramen — broth + noodles perfected over decades in Japan"),
    frozenset({"broth", "rice"}): ("porridge", "Congee/porridge — rice simmered in broth, the comfort food of Asia"),
    frozenset({"broth", "meat"}): ("stew", "Meat broth becomes stew — slow-cooked perfection"),
    frozenset({"broth", "vegetable"}): ("soup", "Vegetable broth becomes soup — the original medicine"),
    frozenset({"broth", "spice"}): ("pho", "Pho — Vietnamese spiced broth simmered for 24 hours"),
    frozenset({"broth", "garlic"}): ("soup", "Garlic broth — the French cure for everything"),
    frozenset({"broth", "egg-food"}): ("soup", "Egg drop soup — silky egg ribbons in hot broth"),
    frozenset({"soup", "cheese"}): ("fondue", "Beer cheese soup — melting cheese into soup creates fondue-like magic"),
    frozenset({"soup", "noodle"}): ("ramen", "Noodle soup — the world's most universal comfort food"),
    frozenset({"soup", "rice"}): ("porridge", "Rice soup (congee/jook) — the go-to sick-day meal in Asia"),
    frozenset({"soup", "bread"}): ("stew", "Bread thickens soup into stew — medieval potage"),
    frozenset({"soup", "cream"}): ("stew", "Cream of mushroom, cream of tomato — cream elevates any soup"),
    frozenset({"soup", "spice"}): ("curry", "Spiced soup → curry — it's all a spectrum"),

    # === Tortilla/Wrap combinations ===
    frozenset({"tortilla", "meat"}): ("taco", "Tacos — Mexico's greatest gift to world cuisine"),
    frozenset({"tortilla", "cheese"}): ("nacho", "Quesadilla — grilled cheese in a tortilla"),
    frozenset({"tortilla", "rice"}): ("burrito", "Burritos wrap rice in a tortilla — San Francisco's Mission style"),
    frozenset({"tortilla", "salsa"}): ("taco", "Salsa on a tortilla — the foundation of Mexican street food"),
    frozenset({"tortilla", "guacamole"}): ("taco", "Guacamole in a tortilla — the avocado taco of dreams"),
    frozenset({"tortilla", "bean"}): ("burrito", "Bean burritos — the protein-packed original"),

    # === Alcohol combinations ===
    frozenset({"beer", "honey"}): ("mead", "Mead — honey wine, possibly humanity's oldest alcoholic drink"),
    frozenset({"wine", "spice"}): ("mead", "Mulled wine — spiced wine has warmed Europeans since Roman times"),
    frozenset({"wine", "fruit"}): ("cider", "Sangria — wine and fruit, Spain's party drink"),
    frozenset({"whiskey", "honey"}): ("mead", "Honey whiskey — the Hot Toddy cure-all"),
    frozenset({"rum", "coconut"}): ("juice", "Piña colada — rum and coconut, tropical paradise in a glass"),
    frozenset({"rum", "sugar"}): ("candy", "Rum balls — sugar and rum, the holiday treat"),
    frozenset({"beer", "bread"}): ("sourdough", "Ancient Egyptians used the same yeast for beer and bread"),
    frozenset({"wine", "cheese"}): ("fondue", "Wine and cheese — the French art of pairing"),

    # === Sauce/Condiment combinations ===
    frozenset({"tomato", "garlic"}): ("salsa", "Salsa — tomatoes and garlic blended into a zesty dip"),
    frozenset({"tomato", "onion"}): ("salsa", "Pico de gallo — fresh chopped tomato and onion"),
    frozenset({"tomato", "spice"}): ("curry", "Spiced tomato → curry base, the foundation of Indian cooking"),
    frozenset({"tomato", "cheese"}): ("pizza", "Margherita pizza — tomato, mozzarella, and basil since 1889"),
    frozenset({"tomato", "pasta"}): ("spaghetti", "Spaghetti al pomodoro — simplicity perfected"),
    frozenset({"tomato", "bread"}): ("bruschetta", "Pan con tomate — Spain's simplest and best tapa"),
    frozenset({"garlic", "olive-oil"}): ("pesto", "Garlic and oil — the Mediterranean flavor base"),
    frozenset({"garlic", "butter"}): ("fondue", "Garlic butter — the sauce that makes everything better"),
    frozenset({"garlic", "cream"}): ("aioli", "Garlic cream sauce — the French answer to mayo"),
    frozenset({"vinegar", "olive-oil"}): ("salad", "Vinaigrette — oil and vinegar, the original salad dressing"),
    frozenset({"salt", "pepper"}): ("spice", "Salt and pepper — the inseparable seasoning duo"),
    frozenset({"soy-sauce", "ginger"}): ("stew", "Soy and ginger — the foundation of East Asian cooking"),
    frozenset({"soy-sauce", "rice"}): ("sushi", "Soy sauce on rice — the simplest Japanese meal"),
    frozenset({"wasabi", "soy-sauce"}): ("sushi", "Wasabi soy sauce — the sushi dipping combo"),
    frozenset({"peanut-butter", "jam"}): ("sandwich", "PB&J — America's iconic school lunch since 1901"),
    frozenset({"peanut-butter", "bread"}): ("sandwich", "Peanut butter sandwich — 3 ingredients, infinite nostalgia"),

    # === Potato combinations ===
    frozenset({"potato", "cheese"}): ("fondue", "Cheese fries, loaded baked potatoes — potato loves cheese"),
    frozenset({"potato", "butter"}): ("muffin", "Buttery mashed potatoes — Thanksgiving's essential side"),
    frozenset({"potato", "cream"}): ("soup", "Cream of potato soup — velvety comfort"),
    frozenset({"potato", "egg-food"}): ("omelette", "Spanish tortilla — potato and egg, tapas perfection"),
    frozenset({"potato", "meat"}): ("stew", "Meat and potatoes — the hearty meal of the working class"),
    frozenset({"potato", "salt"}): ("nacho", "Salted potato chips — invented by accident in 1853"),
    frozenset({"potato", "onion"}): ("soup", "Potato and onion soup — humble ingredients, amazing flavor"),

    # === Fruit combinations ===
    frozenset({"fruit", "sugar"}): ("jam", "Jam — fruit preserved with sugar since ancient Persia"),
    frozenset({"fruit", "cream"}): ("mousse", "Fruit mousse — whipped cream meets fresh fruit"),
    frozenset({"fruit", "milk"}): ("smoothie", "Fruit smoothie — the blender revolution of the 1930s"),
    frozenset({"fruit", "yogurt"}): ("smoothie", "Fruit yogurt — a health food staple worldwide"),
    frozenset({"fruit", "dough"}): ("pie", "Fruit pie — every culture puts fruit in pastry"),
    frozenset({"fruit", "ice-cream"}): ("sorbet", "Fruit sorbet — frozen fruit dessert since the Persian Empire"),
    frozenset({"fruit", "chocolate"}): ("fondue", "Chocolate fondue — dipping fruit in chocolate is pure joy"),
    frozenset({"fruit", "honey"}): ("jam", "Fruit and honey preserves — nature's candy"),
    frozenset({"grape", "sugar"}): ("wine", "Wine — grapes fermented with sugar, 8,000 years of tradition"),
    frozenset({"mango", "milk"}): ("smoothie", "Mango lassi — India's beloved yogurt-mango smoothie"),
    frozenset({"coconut", "milk"}): ("curry", "Coconut milk — the creamy base of Thai and Indian curries"),
    frozenset({"coconut", "chocolate"}): ("candy", "Chocolate coconut — the Mounds/Bounty bar combination"),
    frozenset({"coconut", "sugar"}): ("candy", "Coconut candy — sweet coconut treats from Brazil to Philippines"),

    # === More specific combos ===
    frozenset({"meat", "bread"}): ("hamburger", "Hamburger — the German-American icon of fast food"),
    frozenset({"meat", "spice"}): ("kebab", "Kebab — spiced meat is a Middle Eastern staple"),
    frozenset({"meat", "rice"}): ("kebab", "Meat and rice — from biryani to Korean bibimbap"),
    frozenset({"meat", "cheese"}): ("hamburger", "Cheeseburger — adding cheese to the burger changed everything"),
    frozenset({"steak", "spice"}): ("kebab", "Spiced steak → kebab, grilled perfection"),
    frozenset({"steak", "salt"}): ("jerky", "Salted steak dried into jerky — ancient preservation"),
    frozenset({"sugar", "butter"}): ("caramel", "Caramel — sugar and butter heated to golden perfection"),
    frozenset({"sugar", "cream"}): ("ice-cream", "Ice cream — sweetened cream frozen into bliss"),
    frozenset({"sugar", "water"}): ("lemonade", "Sugar water — the simple syrup base for all drinks"),
    frozenset({"sugar", "fruit"}): ("jam", "Sugar preserves fruit — jam-making since ancient times"),
    frozenset({"sugar", "flour"}): ("cake", "Sugar and flour — the backbone of all cakes"),
    frozenset({"sugar", "egg-food"}): ("meringue", "Meringue — whipped sugar and egg whites, light as air"),
    frozenset({"honey", "water"}): ("mead", "Mead — honey wine, the drink of Vikings and pharaohs"),
    frozenset({"salt", "meat"}): ("jerky", "Salt-cured meat — humanity's first preservation method"),
    frozenset({"salt", "fish"}): ("caviar", "Salt-cured fish eggs = caviar — the luxury of the sea"),
    frozenset({"salt", "vegetable"}): ("kimchi", "Salted vegetables → kimchi — Korean fermentation magic"),
    frozenset({"vinegar", "vegetable"}): ("pickle", "Pickling — vinegar preserves vegetables for months"),
    frozenset({"vinegar", "rice"}): ("sushi", "Sushi rice is seasoned with rice vinegar — it's what makes sushi, sushi"),
    frozenset({"onion", "meat"}): ("kebab", "Onion and meat on a skewer — the world's oldest BBQ"),
    frozenset({"onion", "bread"}): ("focaccia", "Onion focaccia — caramelized onions on Italian bread"),
    frozenset({"ginger", "rice"}): ("sushi", "Ginger cleanses the palate between sushi bites"),
    frozenset({"ginger", "tea"}): ("kombucha", "Ginger tea — warming remedy used for 5,000 years"),
    frozenset({"olive", "bread"}): ("bruschetta", "Olive bread — a Mediterranean staple since antiquity"),
    frozenset({"olive", "cheese"}): ("salad", "Greek salad — olives, feta, and fresh vegetables"),
    frozenset({"cream", "sugar"}): ("ice-cream", "Cream + sugar → ice cream — the frozen dessert revolution"),
    frozenset({"cream", "coffee"}): ("espresso", "Espresso con panna — cream atop a shot of espresso"),
    frozenset({"cream", "chocolate"}): ("mousse", "Chocolate mousse — cream whipped with chocolate"),
    frozenset({"cream", "butter"}): ("cheese", "Churning cream creates butter — and eventually cheese"),
    frozenset({"yogurt", "fruit"}): ("smoothie", "Fruit yogurt parfait — healthy breakfast champion"),
    frozenset({"yogurt", "honey"}): ("granola", "Yogurt and honey — the Greek breakfast tradition"),
    frozenset({"yogurt", "spice"}): ("curry", "Spiced yogurt — raita, the cooling side to every curry"),
    frozenset({"yogurt", "garlic"}): ("tzatziki", "Tzatziki — Greek yogurt-garlic-cucumber sauce"),
    frozenset({"ice-cream", "fruit"}): ("sorbet", "Fruit ice cream → sorbet — the dairy-free frozen treat"),
    frozenset({"ice-cream", "cookie"}): ("cake", "Ice cream sandwich — cookies hugging frozen cream"),
    frozenset({"ice-cream", "coffee"}): ("tiramisu", "Affogato — drowning ice cream in espresso"),
    frozenset({"cake", "cream"}): ("tiramisu", "Layer cake with cream — the architecture of dessert"),
    frozenset({"cake", "chocolate"}): ("tiramisu", "Chocolate cake — the world's most requested birthday cake"),
    frozenset({"cake", "fruit"}): ("pie", "Fruit cake — the holiday tradition everyone jokes about"),
    frozenset({"cookie", "cream"}): ("cake", "Oreos — sandwich cookies with cream filling since 1912"),
    frozenset({"cookie", "chocolate"}): ("cake", "Chocolate chip cookies — invented by accident in 1938"),
    frozenset({"noodle", "broth"}): ("ramen", "Ramen — Japanese noodle soup, the perfect late-night meal"),
    frozenset({"noodle", "soy-sauce"}): ("ramen", "Soy sauce noodles — quick and umami-packed"),
    frozenset({"noodle", "spice"}): ("ramen", "Spicy noodles — from Sichuan dan dan to Korean fire noodles"),
    frozenset({"noodle", "meat"}): ("pho", "Pho — Vietnamese noodle soup with tender meat"),
    frozenset({"noodle", "vegetable"}): ("ramen", "Veggie noodle stir-fry — healthy and fast"),
    frozenset({"corn", "butter"}): ("popcorn", "Buttered corn → popcorn — the movie theater essential"),
    frozenset({"corn", "cheese"}): ("nacho", "Corn chips with cheese — nachos!"),
    frozenset({"corn", "flour"}): ("tortilla", "Corn flour → tortilla — the Mesoamerican staple"),
    frozenset({"corn", "salt"}): ("popcorn", "Salted corn → popcorn — the simplest snack"),
    frozenset({"herb", "olive-oil"}): ("pesto", "Pesto — herbs blended with olive oil, Genoa's green gold"),
    frozenset({"herb", "butter"}): ("cooking", "Herb butter — compound butter elevates any dish"),
    frozenset({"herb", "cheese"}): ("pesto", "Herbed cheese — from boursin to chèvre"),
    frozenset({"herb", "bread"}): ("focaccia", "Herb bread — rosemary focaccia is irresistible"),
    frozenset({"maple-syrup", "pancake"}): ("waffle", "Maple syrup on pancakes — a North American breakfast ritual"),
    frozenset({"maple-syrup", "butter"}): ("caramel", "Maple butter — the sweet spread of Quebec"),
    frozenset({"caramel", "cream"}): ("candy", "Caramel cream — the filling of every great candy bar"),
    frozenset({"caramel", "fruit"}): ("candy", "Caramel-dipped fruit — the fall carnival classic"),
    frozenset({"batter", "fruit"}): ("pancake", "Fruit pancakes — batter with berries, a breakfast treat"),
    frozenset({"batter", "sugar"}): ("waffle", "Sweet batter → waffles, the Belgian breakfast"),
    frozenset({"batter", "milk"}): ("crepe", "Thin milk batter → crêpes, France's street food"),
    frozenset({"batter", "egg-food"}): ("pancake", "Egg batter → fluffy pancakes"),
    frozenset({"batter", "chocolate"}): ("cake", "Chocolate batter → the world's favorite cake"),
    frozenset({"gravy", "meat"}): ("roast", "Gravy and roast meat — Sunday dinner perfection"),
    frozenset({"gravy", "potato"}): ("stew", "Mashed potatoes with gravy — comfort food royalty"),
    frozenset({"gravy", "bread"}): ("stew", "Bread soaked in gravy — the working-class feast"),
    frozenset({"salsa", "corn"}): ("nacho", "Chips and salsa — the Mexican appetizer of the Americas"),
    frozenset({"salsa", "meat"}): ("taco", "Salsa on meat tacos — the street food of Mexico"),
    frozenset({"hummus", "bread"}): ("falafel", "Hummus on pita bread — the Middle Eastern lunch staple"),
    frozenset({"miso", "noodle"}): ("ramen", "Miso ramen — Sapporo's iconic noodle soup"),
    frozenset({"miso", "tofu"}): ("soup", "Miso soup with tofu — served at every Japanese meal"),
    frozenset({"soy-sauce", "wasabi"}): ("sushi", "The sushi condiment duo — soy for umami, wasabi for heat"),
    frozenset({"tofu", "spice"}): ("curry", "Spiced tofu — mapo tofu, Sichuan's numbing masterpiece"),
    frozenset({"tofu", "soy-sauce"}): ("miso", "Tofu in soy sauce — both come from soybeans"),
    frozenset({"seaweed", "rice"}): ("sushi", "Nori and rice — the base of every sushi roll"),
    frozenset({"seaweed", "fish"}): ("sushi", "Fish wrapped in seaweed — nigiri and maki sushi"),
    frozenset({"kimchi", "rice"}): ("stew", "Kimchi fried rice — Korea's favorite way to use old kimchi"),
    frozenset({"pickle", "bread"}): ("sandwich", "Pickle on a sandwich — the deli essential"),
    frozenset({"pickle", "meat"}): ("sandwich", "Pickles and pastrami — the New York deli classic"),
    frozenset({"prosciutto", "cheese"}): ("sandwich", "Prosciutto and mozzarella — Italian antipasto perfection"),
    frozenset({"prosciutto", "bread"}): ("sandwich", "Prosciutto on crusty bread — the Italian panino"),
    frozenset({"caviar", "bread"}): ("bruschetta", "Caviar on toast — the luxury canapé of Russian aristocrats"),
    frozenset({"truffle", "pasta"}): ("ravioli", "Truffle ravioli — the most expensive pasta dish on earth"),
    frozenset({"truffle", "egg-food"}): ("omelette", "Truffle omelette — a French luxury in three ingredients"),
    frozenset({"truffle", "risotto"}): ("risotto", "Truffle risotto — white truffles shaved over rice is pure gold"),
}

# =============================================================================
# 6. HUMAN_DOMAIN_MAP: tool/domain element → profession result
#    Format: { element_id: (profession_id, reasoning) }
# =============================================================================
HUMAN_DOMAIN_MAP = {
    # Weapons → Warriors
    "sword": ("knight", "Knights wielded swords as symbols of honor and chivalry"),
    "spear": ("gladiator", "Gladiators fought with spears in Roman arenas"),
    "shield": ("guard", "Guards carry shields to protect people and places"),
    "bow": ("ranger", "Rangers are master archers, patrolling the wilderness"),
    "arrow": ("ranger", "Arrows require a skilled ranger to hit their mark"),
    "dagger": ("assassin", "Assassins favor daggers — silent, concealable, and deadly"),
    "mace": ("knight", "Maces were designed to defeat armor — a knight's backup weapon"),
    "gun": ("hunter", "Hunters use firearms for game — the modern evolution of the bow"),
    "helmet": ("centurion", "Roman centurions wore crested helmets to lead their legions"),
    "armor": ("knight", "A knight's armor could weigh 50 pounds and cost a fortune"),
    "crossbow": ("ranger", "Crossbows democratized archery — less training, more power"),
    "catapult": ("centurion", "Roman centurions deployed catapults during sieges"),
    "trebuchet": ("centurion", "The trebuchet — the medieval superweapon of siege warfare"),

    # Medical tools → Medical professions
    "scalpel": ("surgeon", "Surgeons wield scalpels with incredible precision"),
    "stethoscope": ("doctor", "The stethoscope — invented in 1816 because a doctor was too shy to press his ear to a woman's chest"),
    "syringe": ("doctor", "Syringes deliver vaccines — the doctor's most impactful tool"),
    "pill": ("pharmacist", "Pharmacists are the pill experts — chemistry meets medicine"),
    "medicine": ("doctor", "Doctors have practiced medicine for over 5,000 years"),
    "bandage": ("paramedic", "Paramedics apply bandages in the field — first responders saving lives"),
    "vaccine": ("doctor", "Edward Jenner's smallpox vaccine in 1796 launched modern medicine"),
    "crutch": ("healer", "Healers help people walk again — crutches are ancient aids"),
    "prosthetic": ("surgeon", "Prosthetic limbs — surgeons give people back their mobility"),
    "wheelchair": ("doctor", "Doctors prescribe wheelchairs to restore independence"),
    "glasses": ("doctor", "Eyeglasses were invented by Italian monks around 1286"),
    "x-ray": ("doctor", "Wilhelm Röntgen discovered X-rays in 1895 — revolutionizing diagnosis"),

    # Science tools → Scientists
    "telescope": ("astronomer", "Galileo pointed his telescope at Jupiter and changed everything"),
    "microscope": ("scientist", "Microscopes revealed the hidden world of cells and microbes"),
    "crucible": ("alchemist", "Alchemists used crucibles to attempt transmuting lead into gold"),
    "experiment": ("scientist", "Scientists live and die by the experiment — the heart of the scientific method"),
    "periodic-table": ("scientist", "Mendeleev arranged 63 elements and predicted ones not yet discovered"),
    "compass": ("navigator", "Navigators used magnetic compasses to cross oceans"),
    "map": ("cartographer", "Cartographers map the world — from Ptolemy to Google Maps"),
    "thermometer": ("scientist", "Galileo invented the thermometer — measuring heat scientifically"),
    "scale": ("scientist", "Scientists use precision scales to measure matter"),
    "centrifuge": ("scientist", "Centrifuges separate substances — essential in biology and chemistry"),
    "spectroscope": ("astronomer", "Spectroscopes reveal what distant stars are made of — by splitting their light"),
    "binoculars": ("navigator", "Navigators scan the horizon with binoculars — watching for land"),
    "sextant": ("navigator", "Sextants let sailors determine latitude by measuring star angles"),

    # Music instruments → Musicians
    "guitar": ("musician", "The guitar — the world's most popular instrument, from blues to rock"),
    "piano": ("musician", "The piano has 88 keys and can play any genre ever created"),
    "violin": ("musician", "Stradivarius violins from the 1700s are worth millions today"),
    "drum": ("musician", "Drums are humanity's oldest instrument — rhythm is primal"),
    "flute": ("musician", "The oldest known instrument is a 43,000-year-old bone flute"),
    "trumpet": ("musician", "Trumpets announce kings and lead jazz bands"),
    "cello": ("musician", "The cello's range is closest to the human voice"),
    "harp": ("musician", "Harps have been played for 5,000 years — the instrument of angels"),
    "saxophone": ("musician", "Adolphe Sax invented the saxophone in 1846 for military bands"),
    "harmonica": ("musician", "The harmonica — small enough for a pocket, soulful enough for the blues"),
    "accordion": ("musician", "Accordions provide the soundtrack from Paris to Buenos Aires"),
    "banjo": ("musician", "The banjo originated from African string instruments brought to America"),
    "ukulele": ("musician", "The ukulele — Hawaii's gift to the world of music"),
    "mandolin": ("musician", "Mandolins give folk and bluegrass their signature twang"),
    "bagpipe": ("musician", "Bagpipes have led Scottish warriors into battle for centuries"),
    "oboe": ("musician", "The oboe tunes the entire orchestra — its A is the standard"),
    "clarinet": ("musician", "Mozart wrote his last concerto for the clarinet"),
    "tuba": ("musician", "The tuba — the foundation of every brass section"),
    "xylophone": ("musician", "Xylophones produce crystal-clear tones from wooden bars"),

    # Art tools → Artists
    "paint": ("artist", "Artists have painted since cave walls in Lascaux 17,000 years ago"),
    "canvas": ("artist", "Canvas replaced wood panels in the Renaissance — lighter, larger art"),
    "easel": ("artist", "Every studio needs an easel — the artist's workstation"),
    "pigment": ("artist", "Artists once ground their own pigments — some were toxic (lead white, arsenic green)"),
    "ink": ("scribe", "Scribes copied texts by hand with ink for millennia before printing"),
    "sculpting": ("artist", "Sculptors turn stone and clay into immortal forms"),
    "pottery": ("potter", "Potters have shaped clay since 29,000 BCE — the oldest craft"),
    "calligraphy": ("scribe", "Calligraphy elevates writing to visual art"),
    "photography": ("artist", "Photography — painting with light since 1826"),
    "drawing": ("artist", "Drawing is the foundation of all visual arts"),

    # Writing tools → Writers
    "pen": ("author", "The pen is mightier than the sword — authors shape history"),
    "quill": ("scribe", "Scribes used goose quill pens for over 1,000 years"),
    "notebook": ("journalist", "Journalists carry notebooks to capture stories as they unfold"),
    "book": ("librarian", "Librarians curate humanity's collected knowledge"),
    "scroll": ("scribe", "Scribes unrolled scrolls to record laws, myths, and histories"),

    # Technology tools → Tech professions
    "code": ("programmer", "Programmers write code — the invisible infrastructure of modern life"),
    "computer": ("programmer", "Computers do exactly what programmers tell them — nothing more, nothing less"),
    "keyboard": ("programmer", "Programmers spend 8+ hours a day at their keyboards"),
    "algorithm": ("programmer", "Algorithms are step-by-step recipes that programmers write for computers"),
    "circuit": ("electrician", "Electricians wire circuits that power our modern world"),
    "robot": ("engineer", "Engineers build robots to automate the impossible"),
    "engine": ("mechanic", "Mechanics keep engines running — the heartbeat of machines"),
    "gear": ("engineer", "Engineers design gears — the teeth that transfer mechanical power"),
    "machine": ("engineer", "Engineers design machines that multiply human capability"),
    "generator": ("electrician", "Electricians install and maintain generators that create power"),
    "battery": ("electrician", "Batteries store electricity — electricians wire them into systems"),
    "wire": ("electrician", "Electricians run wire through buildings — the nervous system of infrastructure"),

    # Craft tools → Craft professions
    "hammer": ("blacksmith", "Blacksmiths have hammered metal into shape for 6,000 years"),
    "anvil": ("blacksmith", "The anvil is the blacksmith's altar — where raw metal becomes useful"),
    "forge-bellows": ("blacksmith", "Bellows blast air into the forge to reach metal-melting temperatures"),
    "axe": ("lumberjack", "Lumberjacks fell trees with axes — the original forest industry"),
    "saw": ("carpenter", "Carpenters cut wood to build — saws have existed since ancient Egypt"),
    "chisel": ("carpenter", "Carpenters chisel joints with precision — no nails needed"),
    "needle": ("tailor", "Tailors wield needles to create clothing — the world's oldest craft tool"),
    "thread": ("weaver", "Weavers turn thread into fabric on looms"),
    "scissors": ("tailor", "Tailors' scissors are sacred — never use them on paper"),
    "fabric": ("tailor", "Tailors transform fabric into garments — wearable art"),
    "loom": ("weaver", "Weavers at the loom create textiles — the Jacquard loom inspired computers"),
    "kiln": ("potter", "Potters fire clay in kilns at 1000°C to create ceramics"),
    "lens": ("glassblower", "Glassblowers shaped the first lenses — enabling microscopes and telescopes"),
    "gem": ("jeweler", "Jewelers cut and set gems — turning raw stone into beauty"),
    "diamond": ("jeweler", "Diamonds are cut by jewelers — the hardest natural material shaped by skill"),
    "gold": ("jeweler", "Jewelers have worked gold since 4000 BCE — the eternal metal"),
    "silver": ("jeweler", "Silversmiths craft jewelry and tableware from the moon's metal"),

    # Agriculture → Farming professions
    "plow": ("farmer", "The plow launched the agricultural revolution — farming feeds civilization"),
    "plough": ("farmer", "Ploughs turn soil for planting — the tool that made cities possible"),
    "sickle": ("farmer", "Farmers have harvested grain with sickles for 10,000 years"),
    "hoe": ("farmer", "The hoe — the most basic and universal farming tool"),
    "tractor": ("farmer", "Tractors mechanized farming — one machine replaces 20 horses"),
    "seed": ("farmer", "Farmers plant seeds — the act that separates civilization from nomadism"),

    # Food tools → Food professions
    "cooking": ("chef", "Chefs elevate cooking to an art form — controlling heat, flavor, and time"),
    "oven": ("baker", "Bakers have used ovens since ancient Egypt to create bread"),
    "kettle": ("brewer", "Brewers use kettles to boil wort — the key step in making beer"),

    # Navigation → Navigation professions
    "ship": ("captain", "Captains command ships — responsibility for crew and cargo"),
    "sailboat": ("sailor", "Sailors have crossed oceans under sail for thousands of years"),
    "submarine": ("diver", "Divers explore the deep — submarines are their ultimate vehicle"),
    "rocket": ("pilot", "Rocket pilots push the boundaries of human exploration"),
    "airplane": ("pilot", "Pilots navigate aircraft through the skies"),
    "helicopter": ("pilot", "Helicopter pilots can hover, land anywhere, and rescue anyone"),

    # Academic/Knowledge → Academic professions
    "school": ("teacher", "Teachers shape every other profession — the most important job"),
    "university": ("professor", "Professors research and teach at the frontier of knowledge"),
    "law": ("lawyer", "Lawyers interpret and argue the law — society's rule enforcers"),
    "justice": ("judge", "Judges render justice — the final word in the courtroom"),
    "camera": ("journalist", "Photojournalists capture history as it happens"),
    "newspaper": ("journalist", "Journalists inform the public — democracy's watchdogs"),

    # Nature tools → Nature professions
    "flower": ("florist", "Florists arrange flowers into living art"),
    "animal": ("veterinarian", "Veterinarians heal animals — doctors for every species but ours"),
    "bone": ("taxidermist", "Taxidermists preserve and mount animal specimens"),
    "herb": ("pharmacist", "Pharmacists evolved from herbalists — plants were the first medicine"),
    "lock": ("locksmith", "Locksmiths have picked and made locks since ancient Egypt"),

    # Stealth/Espionage
    "trap": ("spy", "Spies set traps — information warfare at its finest"),
    "key": ("locksmith", "Locksmiths craft keys — the guardians of security"),
    "magnifying-glass": ("spy", "Detectives and spies examine clues with magnifying glasses"),

    # Mining/Materials
    "pick": ("miner", "Miners use picks to extract ore from deep underground"),
    "shovel": ("miner", "Miners dig with shovels — unearthing the earth's treasures"),
    "drill": ("miner", "Drill technology lets miners reach deeper deposits"),
    "iron": ("blacksmith", "Blacksmiths forge iron into tools, weapons, and horseshoes"),
    "steel": ("blacksmith", "Steel is the blacksmith's finest material — strong and flexible"),
    "copper": ("electrician", "Copper conducts electricity — electricians work with it daily"),
    "pliers": ("plumber", "Plumbers use pliers to grip pipes — keeping water flowing"),
    "wrench": ("mechanic", "Mechanics reach for wrenches — the universal fixing tool"),

    # Religion/Spirituality
    "prayer": ("monk", "Monks dedicate their lives to prayer and contemplation"),
    "church": ("monk", "Monks serve in churches and monasteries"),
    "temple": ("monk", "Buddhist monks maintain temples and practice meditation"),
    "monastery": ("monk", "Monasteries are where monks live, pray, and preserve knowledge"),
}

# =============================================================================
# 7. MAGIC_ANIMAL_MAP: animal + magic → mythical creature
#    Format: { animal_id: (mythical_id, reasoning) }
# =============================================================================
MAGIC_ANIMAL_MAP = {
    "horse": ("unicorn", "Add a magical horn to a horse and you get the unicorn — symbol of purity"),
    "lizard": ("dragon", "Dragons are essentially magical lizards scaled up to terrifying size"),
    "snake": ("basilisk", "The basilisk — king of serpents, whose gaze turns you to stone"),
    "wolf": ("werewolf", "Werewolves blur the line between human and wolf with dark magic"),
    "cat": ("familiar", "Witches' familiars are magical cats — companions in sorcery"),
    "bird": ("phoenix", "The phoenix dies in fire and is reborn — the most magical bird"),
    "eagle": ("griffin", "Griffins have the head and wings of an eagle with a lion's body"),
    "lion": ("chimera", "The chimera combines lion, goat, and snake — a magical hybrid"),
    "spider": ("tarantula", "Magic enlarges spiders into the giant tarantulas of fantasy"),
    "fish": ("kraken", "The kraken — a magically massive sea creature from Norse legend"),
    "deer": ("centaur", "Magic merges deer-like grace with human intelligence — the centaur"),
    "goose": ("roc", "The roc is a goose magnified by magic to carry elephants"),
    "chicken": ("cockatrice", "The cockatrice hatches from a rooster egg incubated by a serpent"),
    "rooster": ("cockatrice", "Cockatrices have a rooster's body and a serpent's tail"),
    "bat": ("vampire", "Vampire bats inspired vampire legends — blood-drinking creatures of the night"),
    "dog": ("cerberus", "Cerberus — the three-headed dog guarding the Greek underworld"),
    "buffalo": ("minotaur", "The Minotaur — half bull, half human, trapped in the Labyrinth"),
    "whale": ("kraken", "The kraken was often confused with whales by terrified sailors"),
    "octopus": ("kraken", "Giant octopuses inspired kraken legends — tentacles from the deep"),
    "squid": ("kraken", "Giant squid reaching 43 feet fuel kraken mythology"),
    "frog": ("naga", "Nagas are magical serpent-beings who control water — frog connection"),
    "turtle": ("hydra", "Hydra's regenerating heads mirror the turtle's longevity — magical endurance"),
    "crocodile": ("dragon", "Chinese dragons evolved from crocodile worship — water dragons"),
    "monkey": ("imp", "Imps are mischievous magical creatures — monkeys of the spirit world"),
    "bear": ("gryphon", "Griffins are as powerful as bears — magic's apex predator"),
    "fox": ("shapeshifter", "Kitsune — magical foxes who shapeshift in Japanese mythology"),
    "elephant": ("treant", "Treants are massive magical beings — elephants of the forest"),
    "sheep": ("satyr", "Satyrs are half-goat/sheep magical forest beings from Greek myth"),
    "ram": ("satyr", "Satyrs have ram horns — the wild magical spirits of Dionysus"),
    "pig": ("ogre", "Ogres are the brutish, pig-like creatures of fairy tales"),
    "boar": ("manticore", "The manticore combines a lion's body with other bestial features — boar-like ferocity"),
    "cow": ("minotaur", "The Minotaur was born from Pasiphaë and a magical bull"),
    "parrot": ("harpy", "Harpies are magical bird-women — shrieking avian terrors"),
    "swan": ("siren", "Sirens sing sailors to their doom — magical swan-like enchantresses"),
    "crow": ("raven", "Ravens are already associated with magic — Odin's messengers"),
    "raven": ("banshee", "Banshees wail like ravens — magical harbingers of death"),
    "owl": ("sphinx", "The sphinx asks riddles — wise as an owl, magical as a lion"),
    "seal": ("kelpie", "Kelpies are magical water horses — selkies are magical seals"),
    "dolphin": ("mermaid", "Mermaids merge human and marine — dolphins inspired the legends"),
    "jellyfish": ("will-o-wisp", "Will-o-wisps glow like magical jellyfish floating in darkness"),
    "scorpion": ("manticore", "Manticores have scorpion tails — venomous magical hybrids"),
    "moth": ("fairy", "Fairies have moth-like wings — magical insects of the forest"),
    "butterfly": ("fairy", "Fairies flutter on butterfly wings through enchanted glades"),
    "dragonfly": ("fairy", "Fairies ride dragonflies in Celtic mythology"),
    "ant": ("golem", "Golems are tireless workers like ants — animated by magic"),
    "bee": ("pixie-dust", "Pixie dust is magical — bees make the closest real-world equivalent"),
    "worm": ("ouroboros", "The ouroboros — a magical worm eating its own tail, symbol of infinity"),
    "salamander": ("fire-elemental", "Medieval alchemists believed salamanders were born from fire"),
    "chameleon": ("changeling", "Changelings are magical shapeshifters — chameleons of the fairy world"),
    "peacock": ("phoenix", "Peacocks and phoenixes both symbolize rebirth and dazzling plumage"),
    "condor": ("thunderbird", "Thunderbirds are massive magical raptors — condors of legend"),
    "falcon": ("thunderbird", "Thunderbirds — Native American magical birds of lightning"),
    "vulture": ("harpy", "Harpies are scavenger bird-women — vultures of Greek mythology"),
    "stork": ("roc", "The roc carries babies? No, elephants — stork legends meet Arabian Nights"),
    "penguin": ("frost-giant", "Frost giants rule the ice — penguins of the magical Arctic"),
    "flamingo": ("phoenix", "Flamingoes and phoenixes both embody fire-colored plumage"),
    "shark": ("kraken", "Kraken and sea monsters — sharks amplified by sorcery"),
    "eel": ("naga", "Nagas are magical serpent-spirits of water — eels are their mortal cousins"),
    "crab": ("golem", "Golems are armored magical constructs — crabs of the arcane world"),
    "lobster": ("hydra", "Lobsters regenerate claws like hydras regrow heads"),
    "starfish": ("undine", "Undines are magical water spirits — starfish are their earthly echoes"),
    "coral": ("enchanted-forest", "Magical underwater forests of living coral"),
    "panda": ("spirit", "Spirit bears in mythology — pandas embody peaceful magic"),
    "tiger": ("chimera", "Chimeras borrow tiger ferocity — magical apex hybrid predators"),
    "jaguar": ("chimera", "Jaguars were sacred to the Maya — magical jungle spirits"),
    "komodo-dragon": ("dragon", "Komodo dragons — the real-world creatures closest to actual dragons"),

    "_default": ("chimera", "Magic transforms animals into mythical hybrid creatures"),
}

# =============================================================================
# 8. SELF_COMBINE_MAP: element + itself → amplified/grouped result
#    Format: { element_id: (result_id, reasoning) }
# =============================================================================
SELF_COMBINE_MAP = {
    # === Nature elements ===
    "water": ("lake", "Water plus water pools into a lake"),
    "fire": ("wildfire", "Fire plus fire spreads into an uncontrollable wildfire"),
    "earth": ("mountain", "Earth piled on earth rises into a mountain"),
    "wind": ("hurricane", "Wind upon wind spirals into a hurricane"),
    "rain": ("flood", "Rain upon rain overwhelms the land — flooding begins"),
    "snow": ("blizzard", "Snow on snow becomes a blizzard — a whiteout of frozen fury"),
    "cloud": ("storm", "Cloud meets cloud and a storm is born — electricity builds between them"),
    "wave": ("tsunami", "Waves amplifying waves become a tsunami — the ocean's most destructive force"),
    "ice": ("glacier", "Ice accumulating over millennia becomes a glacier — rivers of frozen time"),
    "lightning": ("storm", "Lightning begets more lightning — a storm intensifies"),
    "thunder": ("storm", "Thunder upon thunder means the storm is directly overhead"),
    "fog": ("mist", "Double fog creates an impenetrable mist — visibility zero"),
    "mist": ("fog", "Mist thickens into fog — the air becomes opaque"),
    "mud": ("swamp", "Mud pools together into a swamp — where land meets water"),
    "sand": ("desert", "Sand stretching to the horizon — a desert is born"),
    "dust": ("sand-storm", "Dust meets dust and the air fills with choking clouds"),
    "lava": ("volcano", "Lava pooling together builds a volcano — the earth's pressure valve"),
    "smoke": ("smog", "Smoke plus smoke creates smog — the toxic haze of cities"),
    "steam": ("geyser", "Concentrated steam pressure erupts as a geyser"),
    "frost": ("ice", "Frost layers build into solid ice — winter's slow construction"),
    "dew": ("puddle", "Dew drops collecting form a puddle — morning's tiny lakes"),
    "puddle": ("lake", "Puddles merge into ponds, ponds into lakes"),
    "lake": ("ocean", "Lakes connecting become seas, seas become the ocean"),
    "river": ("delta", "A river splitting and recombining creates a delta"),
    "stream": ("river", "Streams join to form rivers — the water cycle in action"),
    "hill": ("mountain", "Hills pushed together form mountain ranges"),
    "mountain": ("ridge", "Mountains lined up form a ridge — the spine of a continent"),
    "boulder": ("cliff", "Boulders stacked by geology create cliffs"),
    "stone": ("boulder", "Stones compacted together form boulders"),
    "pebble": ("gravel", "Pebbles collected together become gravel"),
    "gravel": ("sand", "Gravel ground down becomes sand — erosion in action"),
    "clay": ("brick", "Clay shaped and doubled makes bricks — the original building block"),
    "island": ("archipelago", "Island plus island creates an archipelago — a chain of islands"),
    "volcano": ("island", "Volcanoes erupting together build volcanic island chains — like Hawaii"),
    "cave": ("cavern", "Caves connecting form vast cavern systems"),
    "crater": ("caldera", "Craters merging form calderas — massive volcanic depressions"),

    # === Plant/Life elements ===
    "tree": ("forest", "Tree after tree creates a forest — Earth's green lungs"),
    "grass": ("prairie", "Grass expanding endlessly becomes a prairie"),
    "flower": ("garden", "Flowers gathered together make a garden — cultivated beauty"),
    "seed": ("garden", "Seeds planted together grow into a garden"),
    "leaf": ("forest", "Leaves upon leaves — the canopy of a forest"),
    "vine": ("jungle", "Vines tangling together create a jungle"),
    "moss": ("bog", "Moss growing on moss creates a spongy bog"),
    "fern": ("jungle", "Ferns multiplying fill the jungle understory"),
    "mushroom": ("fungus", "Mushrooms are just the fruiting bodies — beneath is a vast fungal network"),
    "root": ("forest", "Root systems intertwine underground — forests are connected below"),
    "algae": ("coral-reef", "Algae colonies form the symbiotic basis of coral reefs"),
    "coral": ("coral-reef", "Coral polyps building together create reef ecosystems"),
    "seaweed": ("kelp-forest", "Seaweed forests — kelp grows up to 2 feet per day"),
    "cell": ("organ", "Cells combining create organs — the building blocks of life"),
    "bacteria": ("biofilm", "Bacteria group into biofilms — microbial cities"),
    "virus": ("mutation", "Viruses replicating and combining drive mutations"),
    "dna": ("genome", "DNA strands together form the complete genome"),
    "gene": ("chromosome", "Genes lined up on a strand form chromosomes"),
    "neuron": ("brain", "Neurons connecting form the brain — 86 billion strong"),
    "spore": ("mold", "Spores germinating together create mold colonies"),

    # === Human/Social elements ===
    "human": ("family", "Humans together form a family — society's fundamental unit"),
    "family": ("community", "Families together form a community — the social fabric"),
    "community": ("village", "Communities growing become villages"),
    "village": ("town", "Villages expanding become towns"),
    "town": ("city", "Towns growing into cities — urbanization in action"),
    "city": ("nation", "Cities united form a nation — civilization scales up"),
    "nation": ("civilization", "Nations cooperating create civilization"),
    "child": ("family", "Children together make a family — the next generation"),
    "man": ("population", "People gathered form a population"),
    "woman": ("population", "People gathered form a population"),

    # === Building elements ===
    "brick": ("wall", "Bricks stacked become walls — the mason's art"),
    "wall": ("house", "Four walls make a house — shelter from the elements"),
    "house": ("village", "Houses clustered become a village — community begins"),
    "door": ("house", "Doors in sequence create rooms in a house"),
    "window": ("lighthouse", "Windows stacked high become a lighthouse — light multiplied"),
    "tower": ("castle", "Towers grouped together form a castle — medieval fortification"),
    "castle": ("citadel", "Castles reinforced become a citadel — the ultimate fortress"),
    "bridge": ("aqueduct", "Bridges chained together form an aqueduct — Roman engineering genius"),
    "road": ("highway", "Roads connected become highways — infrastructure at scale"),
    "plank": ("bridge", "Planks laid across a gap create a bridge"),
    "rope": ("net", "Ropes woven together create a net"),
    "wire": ("circuit", "Wires connected form circuits — the nervous system of electronics"),
    "chain": ("armor", "Chain links woven together become chainmail armor"),
    "nail": ("wall", "Nails holding planks together — walls are built nail by nail"),

    # === Knowledge/Abstract elements ===
    "letter": ("word", "Letters combined form words — the atoms of language"),
    "word": ("book", "Words accumulated fill a book — captured thought"),
    "book": ("library", "Books collected create a library — humanity's memory palace"),
    "idea": ("philosophy", "Ideas debating ideas become philosophy — the love of wisdom"),
    "thought": ("wisdom", "Thoughts refined over time become wisdom"),
    "story": ("novel", "Stories woven together become a novel — long-form narrative"),
    "poem": ("anthology", "Poems collected become an anthology"),
    "song": ("album", "Songs grouped form an album — a musical journey"),
    "melody": ("symphony", "Melodies layered create a symphony — orchestral architecture"),
    "music": ("concert", "Music performed together is a concert — shared vibration"),
    "number": ("mathematics", "Numbers combined create mathematics — the language of the universe"),
    "code": ("program", "Lines of code assembled become a program"),
    "algorithm": ("program", "Algorithms chained together form a complete program"),
    "myth": ("religion", "Myths collected and codified become religion"),
    "legend": ("myth", "Legends passed down and embellished become myth"),
    "law": ("justice", "Laws applied equally create a justice system"),
    "question": ("philosophy", "Questions building on questions — that's philosophy"),
    "answer": ("knowledge", "Answers accumulated become knowledge"),
    "experiment": ("discovery", "Experiments repeated lead to discovery"),
    "discovery": ("science", "Discoveries building on each other — that's science"),

    # === Space elements ===
    "star": ("constellation", "Stars grouped by imagination form constellations — sky stories"),
    "planet": ("galaxy", "Planets orbit stars, stars form galaxies — cosmic architecture"),
    "galaxy": ("universe", "Galaxies clustered together form the observable universe"),
    "moon": ("planetary-ring", "Moons that shatter form planetary rings — like Saturn's"),
    "asteroid": ("asteroid-belt", "Asteroids grouped together form the asteroid belt between Mars and Jupiter"),
    "comet": ("meteor-shower", "Comets leaving debris trails create meteor showers"),
    "meteor": ("meteor-shower", "Meteors arriving together create a shower — celestial fireworks"),
    "nebula": ("galaxy", "Nebulae are stellar nurseries — gas clouds birthing galaxies"),
    "nova": ("supernova", "A nova going nova again creates a supernova — stellar apocalypse"),
    "black-hole": ("multiverse", "Black holes may connect to other universes — a multiverse portal"),
    "sun": ("binary-star", "Two suns orbiting each other — a binary star system"),
    "satellite-dish": ("seti", "Satellite dishes working together search for extraterrestrial intelligence"),

    # === Material elements ===
    "iron": ("steel", "Iron refined and combined becomes steel — stronger together"),
    "gold": ("treasure", "Gold collected becomes a treasure — every dragon's hoard"),
    "silver": ("jewelry", "Silver worked together becomes jewelry"),
    "copper": ("bronze", "Copper alloyed with itself (and tin) creates bronze"),
    "diamond": ("crown", "Diamonds set together form a crown — the ultimate symbol of power"),
    "crystal": ("gem", "Crystals refined become gems — nature's perfect geometry"),
    "glass": ("lens", "Glass pieces shaped together form lenses — bending light"),
    "paper": ("book", "Papers bound together become a book"),
    "thread": ("fabric", "Threads woven together become fabric"),
    "fabric": ("clothing", "Fabric sewn together becomes clothing"),
    "wool": ("clothing", "Wool spun and doubled makes warm clothing"),
    "leather": ("armor", "Leather layered becomes armor — the first body protection"),
    "candle": ("chandelier", "Candles grouped on a frame make a chandelier — medieval luxury lighting"),
    "coin": ("money", "Coins accumulated become money — wealth made countable"),
    "money": ("wealth", "Money grows into wealth — the measure of economic power"),
    "wealth": ("treasure", "Wealth hoarded becomes treasure"),

    # === Animal elements ===
    "wolf": ("wolf", "A pair of wolves forms a pack — social hunters"),
    "ant": ("colony", "Ants combined form a colony — nature's superorganism"),
    "bee": ("nest", "Bees combined form a hive — 60,000 workers in perfect coordination"),
    "fish": ("reef", "Fish schooling together inhabit reefs — safety in numbers"),
    "bird": ("nest", "Birds paired build a nest — the start of a new generation"),
    "egg": ("nest", "Eggs gathered in a nest — incubation begins"),
    "feather": ("bird", "Feathers assembled make a bird — evolution's flight suit"),
    "spider": ("web", "Spiders weaving together create elaborate webs"),
    "whale": ("ocean", "Whales gathering — the ocean teems with the largest animals ever"),
    "shark": ("ocean", "Sharks schooling — the ocean's apex predators in force"),
    "rabbit": ("population", "Rabbits doubling — their legendary reproduction rate"),
    "mouse": ("population", "Mice populations explode — doubling every 3 weeks"),
    # bacteria duplicate removed — already in Life section above

    # === Technology elements ===
    "computer": ("supercomputer", "Computers linked together form a supercomputer — parallel processing power"),
    "server": ("network", "Servers connected create a network — the backbone of the internet"),
    "transistor": ("processor", "Billions of transistors form a processor — modern CPUs"),
    "bit": ("byte", "8 bits make a byte — the fundamental unit of digital data"),
    "byte": ("data", "Bytes accumulated become data — the raw material of the digital age"),
    "pixel": ("screen", "Millions of pixels together create a screen — digital images"),
    "battery": ("power-grid", "Batteries connected form a power grid — stored energy at scale"),
    "solar-panel": ("power-plant", "Solar panels arrayed become a power plant — harvesting sunlight"),
    "lens": ("telescope", "Lenses combined create a telescope — seeing the cosmos"),
    "mirror": ("telescope", "Mirrors aligned create reflecting telescopes — Hubble uses mirrors"),
    "magnet": ("generator", "Magnets spinning together generate electricity — Faraday's discovery"),
    "gear": ("machine", "Gears meshing together create machines — mechanical advantage multiplied"),
    "wheel": ("machine", "Wheels and axles together form the simplest machine"),
    "spring": ("clock", "Springs driving springs — the mechanism of clockwork"),

    # === Abstract/Emotion elements ===
    "love": ("family", "Love doubled creates family — the strongest bond"),
    "fear": ("nightmare", "Fear amplified becomes a nightmare — terror without escape"),
    "joy": ("ecstasy", "Joy intensified becomes ecstasy — the peak of happiness"),
    "anger": ("war", "Anger meeting anger escalates to war — conflict amplified"),
    "sadness": ("despair", "Sadness deepening becomes despair"),
    "hope": ("faith", "Hope reinforced becomes faith — believing without seeing"),
    "dream": ("imagination", "Dreams building on dreams become imagination — the creative engine"),
    "memory": ("nostalgia", "Memories layered become nostalgia — the bittersweet past"),
    "courage": ("hero", "Courage doubled makes a hero — bravery in action"),
    "wisdom": ("philosophy", "Wisdom seeking wisdom is the definition of philosophy"),
    "knowledge": ("encyclopedia", "Knowledge compiled becomes an encyclopedia — organized understanding"),
    "curiosity": ("discovery", "Curiosity upon curiosity leads to discovery"),
    "creativity": ("art", "Creativity expressed becomes art — imagination made tangible"),
    "magic": ("miracle", "Magic amplified becomes a miracle — the impossible made real"),
    "light": ("laser", "Light coherent and amplified becomes a laser — focused photon power"),
    "darkness": ("void", "Darkness intensified becomes the void — the absence of everything"),
    "energy": ("plasma", "Energy concentrated becomes plasma — the fourth state of matter"),
    "sound": ("echo", "Sound bouncing off itself creates echoes — acoustic feedback"),
    "time": ("infinity", "Time extended infinitely — the endless dimension"),
    "space": ("multiverse", "Space expanded beyond itself implies a multiverse"),
    "gravity": ("black-hole", "Gravity concentrated creates a black hole — spacetime's ultimate trap"),
    "pressure": ("diamond", "Pressure doubled creates diamonds — carbon's most beautiful form"),
    "heat": ("plasma", "Extreme heat creates plasma — stripping electrons from atoms"),
    "cold": ("absolute-zero", "Cold upon cold approaches absolute zero — molecular motion stops"),
    "speed": ("light-year", "Speed maximized measures in light-years — cosmic distances"),

    # === Fantasy elements ===
    "dragon": ("hydra", "Two dragons? That's basically a hydra — multiple heads of fire"),
    "ghost": ("banshee", "Ghosts amplified become banshees — wailing spirits of dread"),
    "zombie": ("army", "Zombies in numbers become an undead army"),
    "skeleton": ("grave", "Skeletons accumulated fill a graveyard"),
    "vampire": ("lich-king", "Vampires at peak power become a lich-king — undead royalty"),
    "unicorn": ("pegasus", "Double the magic — a unicorn gains wings to become a pegasus"),
    "phoenix": ("phoenix-egg", "A phoenix reborn creates its own egg — the cycle of rebirth"),
    "knight": ("army", "Knights assembled form an army — medieval military power"),
    "king": ("empire", "Kings united form an empire — Alexander's dream"),
    "queen": ("empire", "Queens allied form an empire — power consolidated"),
    "wizard": ("arcane-tome", "Wizards combining knowledge fill an arcane tome"),
    "spell": ("spell-book", "Spells collected fill a spell-book — a wizard's greatest treasure"),
    "potion": ("elixir", "Potions refined become an elixir — the ultimate alchemical creation"),
    "rune": ("enchantment", "Runes combined create an enchantment — ancient magical writing"),
    "wand": ("staff-of-power", "Wands merged create a staff of power — amplified magic"),
    "sword": ("thunder-hammer", "Two swords forged together create a legendary weapon of power"),
}
